# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clu < Formula
  desc "A terminal interface for the commandlineuser.com CLI catalogue"
  homepage "https://commandlineuser.com"
  version "1.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ali5ter/clu/releases/download/v1.2.2/clu_darwin_amd64.tar.gz"
      sha256 "e053cf8d837cddb726e0d265e64b9cd3e3af13d2ad55d2781740527b2d70c077"

      define_method(:install) do
        bin.install "clu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ali5ter/clu/releases/download/v1.2.2/clu_darwin_arm64.tar.gz"
      sha256 "e488cf05bb3287150d76274b09a25c53d27659967b7841c7942699475d2abce3"

      define_method(:install) do
        bin.install "clu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ali5ter/clu/releases/download/v1.2.2/clu_linux_amd64.tar.gz"
      sha256 "69168435b25fad0a78d6d592cb26c7de01b64c4edf4e27dbb63c9b1f73dac77e"
      define_method(:install) do
        bin.install "clu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ali5ter/clu/releases/download/v1.2.2/clu_linux_arm64.tar.gz"
      sha256 "e5d116c7af98cde7272700c30c48c12f078718a9d98b35a2fedcc8075264e1ed"
      define_method(:install) do
        bin.install "clu"
      end
    end
  end

  test do
    system "#{bin}/clu", "--version"
  end
end
