# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clu < Formula
  desc "A terminal interface for the commandlineuser.com CLI catalogue"
  homepage "https://commandlineuser.com"
  version "1.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ali5ter/clu/releases/download/v1.4.0/clu_darwin_amd64.tar.gz"
      sha256 "f3b5c81b9f7516cb60d766ca17a318f13f7ef575f54a3aaa898a63a275283e34"

      define_method(:install) do
        bin.install "clu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ali5ter/clu/releases/download/v1.4.0/clu_darwin_arm64.tar.gz"
      sha256 "e4ba4039ccfb41f060bf7a1275e5cd1377800f4b3d89e58266294ea3eb737605"

      define_method(:install) do
        bin.install "clu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ali5ter/clu/releases/download/v1.4.0/clu_linux_amd64.tar.gz"
      sha256 "2f7410899a4c6567cbf35e7d20da4cb8b0c3c47105abd0b9110fe3499772bca7"
      define_method(:install) do
        bin.install "clu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ali5ter/clu/releases/download/v1.4.0/clu_linux_arm64.tar.gz"
      sha256 "f73466475728b59fddd0857615605935fa4c421792a22b5511de0f94bf9e202d"
      define_method(:install) do
        bin.install "clu"
      end
    end
  end

  test do
    system "#{bin}/clu", "--version"
  end
end
