# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Unspool < Formula
  desc "A subscription-first, Shorts-free YouTube TUI"
  homepage "https://github.com/ali5ter/unspool"
  version "1.6.3"
  license "MIT"

  depends_on "chafa"
  depends_on "mpv"
  depends_on "yt-dlp"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ali5ter/unspool/releases/download/v1.6.3/unspool_darwin_amd64.tar.gz"
      sha256 "673f7e44ea8653aa3b8be4e9817cc06f6ded609c857ece7bfa0405d8cb7b63d3"

      define_method(:install) do
        bin.install "unspool"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ali5ter/unspool/releases/download/v1.6.3/unspool_darwin_arm64.tar.gz"
      sha256 "30285847113fe717d0296d7051d2f3049ff62196a6a36bed30358a9bdf439b4e"

      define_method(:install) do
        bin.install "unspool"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ali5ter/unspool/releases/download/v1.6.3/unspool_linux_amd64.tar.gz"
      sha256 "f76ba5b25cf7974f0dd99c88ad1ff6468bb6aed9483d730579c8281f35526db9"
      define_method(:install) do
        bin.install "unspool"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ali5ter/unspool/releases/download/v1.6.3/unspool_linux_arm64.tar.gz"
      sha256 "de926299fcbcf9f5b5da0485d927246e20b5e862b568aea6e70518696d44c982"
      define_method(:install) do
        bin.install "unspool"
      end
    end
  end

  test do
    system "#{bin}/unspool", "--version"
  end
end
