# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wwlog < Formula
  desc "Browse and export your Weight Watchers food log from the terminal"
  homepage "https://github.com/ali5ter/wwlog"
  version "1.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ali5ter/wwlog/releases/download/v1.8.0/wwlog_darwin_amd64.tar.gz"
      sha256 "bdd3a2f3ac196f485b6feff397fbd6055acb9ad3c3cd2874169fba4a44d2ca19"

      define_method(:install) do
        bin.install "wwlog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ali5ter/wwlog/releases/download/v1.8.0/wwlog_darwin_arm64.tar.gz"
      sha256 "454b8e3924b7376062c48f5033f8d9e745b940ade6e2f39d44dca79cdc954629"

      define_method(:install) do
        bin.install "wwlog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ali5ter/wwlog/releases/download/v1.8.0/wwlog_linux_amd64.tar.gz"
      sha256 "fa542fb989affff2e037f8bf009a937c961818c194eb89814029c3348ba48235"
      define_method(:install) do
        bin.install "wwlog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ali5ter/wwlog/releases/download/v1.8.0/wwlog_linux_arm64.tar.gz"
      sha256 "725340a90db0d72cd73ea49dd842c957abf3ee259e657aec69dffc7cfc3cdd26"
      define_method(:install) do
        bin.install "wwlog"
      end
    end
  end

  test do
    system "#{bin}/wwlog", "--version"
  end
end
